# workflows/benchmark-paradedb.yml
#
# Benchmark ParadeDB
# Benchmark ParadeDB's performance on a nightly basis. This workflow can also be triggered
# manually to benchmark other systems on one-off basis, to compare against ParadeDB.

name: Benchmark ParadeDB

on:
  schedule:
    - cron: "1 0 * * 1,2,3,4,5" # Run once per day on weekdays (days of the week 1-5) at 00:01 UTC
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "benchmarks/**"
  workflow_dispatch:
    inputs:
      name:
        description: "Select the system to benchmark"
        default: "paradedb"
        type: choice
        options:
          - paradedb
          - tsquery
          - elasticsearch
          - typesense

concurrency:
  group: benchmark-paradedb-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark-paradedb:
    name: Benchmark ParadeDB
    runs-on: ubuntu-latest-m # Size: 4-cores · 16 GB RAM · 150 GB SSD

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Configure System to Benchmark
        id: system
        run: echo "system_to_benchmark=${{ github.event.inputs.name || 'paradedb' }}" >> $GITHUB_OUTPUT

      # The '-t local' tag is used for benchmark-paradedb.sh and ignored by other scripts
      - name: Run Benchmarking Script
        working-directory: benchmarks/
        run: ./benchmark-${{ steps.system.outputs.system_to_benchmark }}.sh -t local

      - name: Print Results
        working-directory: benchmarks/out/
        run: cat benchmark_${{ steps.system.outputs.system_to_benchmark }}.csv

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Benchmark ParadeDB Workflow failed on ${{ steps.system.outputs.system_to_benchmark }} -- investigate immediately!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
